services: 

  flightmanifest:
    type: ecs
    artifacts:
      dev: 
        type: docker_artifactory
        image: ebs/eservicecheckin/flightmanifest

  phonevalidation:
    type: ecs
    artifacts:
      dev: 
        type: docker_artifactory
        image: ebs/eservicecheckin/phonevalidation

  tap:
    type: ecs
    artifacts:
      dev: 
        type: docker_artifactory
        image: ebs/eservicecheckin/tap


  tcd:
    type: ecs
    artifacts:
      dev: 
        type: docker_artifactory
        image: ebs/eservicecheckin/tcd

environments:
  dev:
    type: nonprod

infrastructure:
  ecs-us-east-1-dev-cluster:
    type: ecs
    environment: dev
    provider: dev
    assign_public_ip: false
    role: arn:aws:iam::560380317052:role/Harness-cwm-tcdecs-dev-us-east-1-Role
    launch_type: fargate
    region: us-east-1
    security_group_ids:
      - sg-09abc2789fc3454e3
    subnet_ids:
      - subnet-060eb67008ada7878
      - subnet-0908d96f54f0a857d
      - subnet-0f4422bb4184c54ae
    vpc: vpc-071b072d13508ae67

providers:
  dev:  
    type: aws
    environment: dev
    sts_role: arn:aws:iam::560380317052:role/Harness-cwm-tcdecs-dev-us-east-1-Role
