app_config:
  artifactorybaseurl: artifactory.ual.com/dockerlocal/airportplatform

# List of all the services for the AppCI
services:
  
  apis-checkinapis:
    type: kubernetes
    tier: backend
    artifacts:
      dev:
        type: docker_artifactory 
        image: airportplatform/dev/apis-checkinapis

  apis-traveldocsverification:
    type: kubernetes
    tier: backend
    artifacts:
      dev:
        type: docker_artifactory 
        image: airportplatform/dev/apis-traveldocsverification

  bag-mgmt:
    type: kubernetes
    tier: backend
    artifacts:
      dev:
        type: docker_artifactory 
        image: airportplatform/dev/bag-mgmt

  bagmgmt-bagfee:
    type: kubernetes
    tier: backend
    artifacts:
      dev:
        type: docker_artifactory 
        image: airportplatform/dev/bagmgmt-bagfee

  bagmgmt-baginfo:
    type: kubernetes
    tier: backend
    artifacts:
      dev:
        type: docker_artifactory 
        image: airportplatform/dev/bagmgmt-baginfo

  bagmgmt-bagpolicy:
    type: kubernetes
    tier: backend
    artifacts:
      dev:
        type: docker_artifactory 
        image: airportplatform/dev/bagmgmt-bagpolicy

  bagmgmt-bagtag:
    type: kubernetes
    tier: backend
    artifacts:
      dev:
        type: docker_artifactory 
        image: airportplatform/dev/bagmgmt-bagtag

  bagmgmt-bagtrack:
    type: kubernetes
    tier: backend
    artifacts:
      dev:
        type: docker_artifactory 
        image: airportplatform/dev/bagmgmt-bagtrack

  checkin-checkininfo:
    type: kubernetes
    tier: backend
    artifacts:
      dev:
        type: docker_artifactory 
        image: airportplatform/dev/checkin-checkininfo

  checkin-payment:
    type: kubernetes
    tier: backend
    artifacts:
      dev:
        type: docker_artifactory 
        image: airportplatform/dev/checkin-payment

  checkin-reconcileflight:
    type: kubernetes
    tier: backend
    artifacts:
      dev:
        type: docker_artifactory 
        image: airportplatform/dev/checkin-reconcileflight

  checkin-travelers:
    type: kubernetes
    tier: backend
    artifacts:
      dev:
        type: docker_artifactory 
        image: airportplatform/dev/checkin-travelers

  checkinapis:
    type: kubernetes
    tier: backend
    artifacts:
      dev:
        type: docker_artifactory 
        image: airportplatform/dev/checkinapis

  dynamocrudoperations:
    type: kubernetes
    tier: backend
    artifacts:
      dev:
        type: docker_artifactory 
        image: airportplatform/dev/dynamocrudoperations

  flifo-search:
    type: kubernetes
    tier: backend
    artifacts:
      dev:
        type: docker_artifactory 
        image: airportplatform/dev/flifo-search

  flight-action-bff:
    type: kubernetes
    tier: backend
    artifacts:
      dev:
        type: docker_artifactory 
        image: airportplatform/dev/flight-action-bff

  flight-action:
    type: kubernetes
    tier: backend
    artifacts:
      dev:
        type: docker_artifactory 
        image: airportplatform/dev/flight-action

  flight-aircraftinformation:
    type: kubernetes
    tier: backend
    artifacts:
      dev:
        type: docker_artifactory 
        image: airportplatform/dev/flight-aircraftinformation

  flight-connection:
    type: kubernetes
    tier: backend
    artifacts:
      dev:
        type: docker_artifactory 
        image: airportplatform/dev/flight-connection

  flight-crewdetails:
    type: kubernetes
    tier: backend
    artifacts:
      dev:
        type: docker_artifactory 
        image: airportplatform/dev/flight-crewdetails

  flight-details-bff:
    type: kubernetes
    tier: backend
    artifacts:
      dev:
        type: docker_artifactory 
        image: airportplatform/dev/flight-details-bff

  flight-detailsrefresh-bff:
    type: kubernetes
    tier: backend
    artifacts:
      dev:
        type: docker_artifactory 
        image: airportplatform/dev/flight-detailsrefresh-bff

  flight-flightaction:
    type: kubernetes
    tier: backend
    artifacts:
      dev:
        type: docker_artifactory 
        image: airportplatform/dev/flight-flightaction

  flight-flightcontrol-bff:
    type: kubernetes
    tier: backend
    artifacts:
      dev:
        type: docker_artifactory 
        image: airportplatform/dev/flight-flightcontrol-bff

  flight-flightcontrol:
    type: kubernetes
    tier: backend
    artifacts:
      dev:
        type: docker_artifactory 
        image: airportplatform/dev/flight-flightcontrol

  flight-flightsummary:
    type: kubernetes
    tier: backend
    artifacts:
      dev:
        type: docker_artifactory 
        image: airportplatform/dev/flight-flightsummary

  flight-inforefresh-bff:
    type: kubernetes
    tier: backend
    artifacts:
      dev:
        type: docker_artifactory 
        image: airportplatform/dev/flight-inforefresh-bff

  flight-information-bff:
    type: kubernetes
    tier: backend
    artifacts:
      dev:
        type: docker_artifactory 
        image: airportplatform/dev/flight-information-bff

  flight-information:
    type: kubernetes
    tier: backend
    artifacts:
      dev:
        type: docker_artifactory 
        image: airportplatform/dev/flight-information

  flight-passengers-boarding-totals:
    type: kubernetes
    tier: backend
    artifacts:
      dev:
        type: docker_artifactory 
        image: airportplatform/dev/flight-passengers-boarding-totals

  flightsearch:
    type: kubernetes
    tier: backend
    artifacts:
      dev:
        type: docker_artifactory 
        image: airportplatform/dev/flightsearch

  global-navigation-bff:
    type: kubernetes
    tier: backend
    artifacts:
      dev:
        type: docker_artifactory 
        image: airportplatform/dev/global-navigation-bff

  global-navigation:
    type: kubernetes
    tier: backend
    artifacts:
      dev:
        type: docker_artifactory 
        image: airportplatform/dev/global-navigation

  loyalty-flightoptions:
    type: kubernetes
    tier: backend
    artifacts:
      dev:
        type: docker_artifactory 
        image: airportplatform/dev/loyalty-flightoptions

  loyalty-managemiles:
    type: kubernetes
    tier: backend
    artifacts:
      dev:
        type: docker_artifactory 
        image: airportplatform/dev/loyalty-managemiles

  loyalty-marketingoffers:
    type: kubernetes
    tier: backend
    artifacts:
      dev:
        type: docker_artifactory 
        image: airportplatform/dev/loyalty-marketingoffers

  loyalty-premierbenefits:
    type: kubernetes
    tier: backend
    artifacts:
      dev:
        type: docker_artifactory 
        image: airportplatform/dev/loyalty-premierbenefits

  loyalty-upgradeoptions:
    type: kubernetes
    tier: backend
    artifacts:
      dev:
        type: docker_artifactory 
        image: airportplatform/dev/loyalty-upgradeoptions

  notification-admin:
    type: kubernetes
    tier: backend
    artifacts:
      dev:
        type: docker_artifactory 
        image: airportplatform/dev/notification-admin

  ovs-manageoversales:
    type: kubernetes
    tier: backend
    artifacts:
      dev:
        type: docker_artifactory 
        image: airportplatform/dev/ovs-manageoversales

  ovs-ovsreport:
    type: kubernetes
    tier: backend
    artifacts:
      dev:
        type: docker_artifactory 
        image: airportplatform/dev/ovs-ovsreport

  pnrcheckin:
    type: kubernetes
    tier: backend
    artifacts:
      dev:
        type: docker_artifactory 
        image: airportplatform/dev/pnrcheckin

  pnrmgmt-emd:
    type: kubernetes
    tier: backend
    artifacts:
      dev:
        type: docker_artifactory 
        image: airportplatform/dev/pnrmgmt-emd

  pnrmgmt-pnr:
    type: kubernetes
    tier: backend
    artifacts:
      dev:
        type: docker_artifactory 
        image: airportplatform/dev/pnrmgmt-pnr

  pnrmgmt-pnrsearch:
    type: kubernetes
    tier: backend
    artifacts:
      dev:
        type: docker_artifactory 
        image: airportplatform/dev/pnrmgmt-pnrsearch

  pnrmgmt-reservation-bff:
    type: kubernetes
    tier: backend
    artifacts:
      dev:
        type: docker_artifactory 
        image: airportplatform/dev/pnrmgmt-reservation-bff

  pnrmgmt-ssr-bff:
    type: kubernetes
    tier: backend
    artifacts:
      dev:
        type: docker_artifactory 
        image: airportplatform/dev/pnrmgmt-ssr-bff

  pnrmgmt-ssr:
    type: kubernetes
    tier: backend
    artifacts:
      dev:
        type: docker_artifactory 
        image: airportplatform/dev/pnrmgmt-ssr

  premierbenefits:
    type: kubernetes
    tier: backend
    artifacts:
      dev:
        type: docker_artifactory 
        image: airportplatform/dev/premierbenefits

  premiumservices-bff:
    type: kubernetes
    tier: backend
    artifacts:
      dev:
        type: docker_artifactory 
        image: airportplatform/dev/premiumservices-bff

  reservation-changeflight:
    type: kubernetes
    tier: backend
    artifacts:
      dev:
        type: docker_artifactory 
        image: airportplatform/dev/reservation-changeflight

  reservation-pnr:
    type: kubernetes
    tier: backend
    artifacts:
      dev:
        type: docker_artifactory 
        image: airportplatform/dev/reservation-pnr

  search:
    type: kubernetes
    tier: backend
    artifacts:
      dev:
        type: docker_artifactory 
        image: airportplatform/dev/search

  seat-mgmt:
    type: kubernetes
    tier: backend
    artifacts:
      dev:
        type: docker_artifactory 
        image: airportplatform/dev/seat-mgmt

  seatmgmt-jumpseat:
    type: kubernetes
    tier: backend
    artifacts:
      dev:
        type: docker_artifactory 
        image: airportplatform/dev/seatmgmt-jumpseat

  seatmgmt-seataction:
    type: kubernetes
    tier: backend
    artifacts:
      dev:
        type: docker_artifactory 
        image: airportplatform/dev/seatmgmt-seataction

  seatmgmt-seatassign:
    type: kubernetes
    tier: backend
    artifacts:
      dev:
        type: docker_artifactory 
        image: airportplatform/dev/seatmgmt-seatassign

  seatmgmt-seatfee:
    type: kubernetes
    tier: backend
    artifacts:
      dev:
        type: docker_artifactory 
        image: airportplatform/dev/seatmgmt-seatfee

  seatmgmt-seatlayout:
    type: kubernetes
    tier: backend
    artifacts:
      dev:
        type: docker_artifactory 
        image: airportplatform/dev/seatmgmt-seatlayout

  seatmgmt-seatrestriction:
    type: kubernetes
    tier: backend
    artifacts:
      dev:
        type: docker_artifactory 
        image: airportplatform/dev/seatmgmt-seatrestriction

  travelers-bff:
    type: kubernetes
    tier: backend
    artifacts:
      dev:
        type: docker_artifactory 
        image: airportplatform/dev/travelers-bff

  traveloptions:
    type: kubernetes
    tier: backend
    artifacts:
      dev:
        type: docker_artifactory 
        image: airportplatform/dev/traveloptions

  user-services:
    type: kubernetes
    tier: backend
    artifacts:
      dev:
        type: docker_artifactory 
        image: airportplatform/dev/user-services

  usersecurity:
    type: kubernetes
    tier: backend
    artifacts:
      dev:
        type: docker_artifactory 
        image: airportplatform/dev/usersecurity

  utility-airportprinters:
    type: kubernetes
    tier: backend
    artifacts:
      dev:
        type: docker_artifactory 
        image: airportplatform/dev/utility-airportprinters

  utility-configvalues:
    type: kubernetes
    tier: backend
    artifacts:
      dev:
        type: docker_artifactory 
        image: airportplatform/dev/utility-configvalues

  utility-currencyexchange:
    type: kubernetes
    tier: backend
    artifacts:
      dev:
        type: docker_artifactory 
        image: airportplatform/dev/utility-currencyexchange

  utility-device-management:
    type: kubernetes
    tier: backend
    artifacts:
      dev:
        type: docker_artifactory 
        image: airportplatform/dev/utility-device-management

  utility-pciproxy:
    type: kubernetes
    tier: backend
    artifacts:
      dev:
        type: docker_artifactory 
        image: airportplatform/dev/utility-pciproxy

  utility-print:
    type: kubernetes
    tier: backend
    artifacts:
      dev:
        type: docker_artifactory 
        image: airportplatform/dev/utility-print

  utility-printers:
    type: kubernetes
    tier: backend
    artifacts:
      dev:
        type: docker_artifactory 
        image: airportplatform/dev/utility-printers

  utility-rbac-admin:
    type: kubernetes
    tier: backend
    artifacts:
      dev:
        type: docker_artifactory 
        image: airportplatform/dev/utility-rbac-admin

  utility-rbac:
    type: kubernetes
    tier: backend
    artifacts:
      dev:
        type: docker_artifactory 
        image: airportplatform/dev/utility-rbac

  utility-reports:
    type: kubernetes
    tier: backend
    artifacts:
      dev:
        type: docker_artifactory 
        image: airportplatform/dev/utility-reports

  utility-security:
    type: kubernetes
    tier: backend
    artifacts:
      dev:
        type: docker_artifactory 
        image: airportplatform/dev/utility-security

  utility-services:
    type: kubernetes
    tier: backend
    artifacts:
      dev:
        type: docker_artifactory 
        image: airportplatform/dev/utility-services

  utility-sharesemulator-bff:
    type: kubernetes
    tier: backend
    artifacts:
      dev:
        type: docker_artifactory 
        image: airportplatform/dev/utility-sharesemulator-bff

  utility-sharesemulator:
    type: kubernetes
    tier: backend
    artifacts:
      dev:
        type: docker_artifactory 
        image: airportplatform/dev/utility-sharesemulator

  utility-tender-management-bff:
    type: kubernetes
    tier: backend
    artifacts:
      dev:
        type: docker_artifactory 
        image: airportplatform/dev/utility-tender-management-bff

  utility-tender-management:
    type: kubernetes
    tier: backend
    artifacts:
      dev:
        type: docker_artifactory 
        image: airportplatform/dev/utility-tender-management

  utility-uilogs:
    type: kubernetes
    tier: backend
    artifacts:
      dev:
        type: docker_artifactory 
        image: airportplatform/dev/utility-uilogs

# Common artifact configuration
artifacts:
  docker_artifactory:
    server: artifactory.ual.com
    repository: dockerlocal
    connector: Jfrog-Artifactory
    auto_trigger: true
    trigger: 
      type: workflow
      name: eks-rolling-basic
      env: 
        name: dev
        infra: us-east-1-aap-atw-devtgw

# Common manifest config for all kubernetes services
manifests:
  kubernetes:
    connector: GitHub-Account-UAL
    repo: AirportOps.AAP.DevSecOps-AAP
    path: SingleTemplate/template
    branch: master
    overrides:
      type: inline
      values: |
        image:
          url: "${app.defaults.artifactorybaseurl}/${env.name}/${service.name}:${artifact.metadata.tag}"

# Workflows to configure
workflows: 
  eks-rolling-basic: {}

# Environment configuration
environments:
  dev:
    type: nonprod

  qa:
    type: nonprod

  stg:
    type: prod

  prd:
    type: prod

# Infrastructure definitions
infrastructure:
  us-east-2-aap-atw-devdrtgw:
    type: kubernetes
    environment: dev
    provider: us-east-2-aap-atw-devdrtgw
    namespace: ${serviceVariable.namespace}

  us-east-1-aap-atw-devtgw:
    type: kubernetes
    environment: dev
    provider: us-east-1-aap-atw-devtgw
    namespace: ${serviceVariable.namespace}

  us-east-1-aap-atw-qatgw:
    type: kubernetes
    environment: qa
    provider: us-east-1-aap-atw-qatgw
    namespace: ${serviceVariable.namespace}

  us-east-2-aap-atw-qadrtgw:
    type: kubernetes
    environment: qa
    provider: us-east-2-aap-atw-qadrtgw
    namespace: ${serviceVariable.namespace}

  us-east-1-aap-test-qatgw:
    type: kubernetes
    environment: qa
    provider: us-east-1-aap-test-qatgw
    namespace: ${serviceVariable.namespace}

  us-east-1-aap-primary-atw-prdtgw:
    type: kubernetes
    environment: prd
    provider: us-east-1-aap-primary-atw-prdtgw
    namespace: ${serviceVariable.namespace}

  us-east-2-aap-atw-prddrtgw:
    type: kubernetes
    environment: prd
    provider: us-east-2-aap-atw-prddrtgw
    namespace: ${serviceVariable.namespace}

# Cloud Providers 
providers:
  us-east-2-aap-atw-devdrtgw:
    type: kubernetes
    environment: dev
    master_url: https://6898A959BEB29879EB78DB7881972045.gr7.us-east-2.eks.amazonaws.com

  us-east-1-aap-atw-devtgw:
    type: kubernetes
    environment: dev
    master_url: https://9FAD057048F1B52E0F1515669463C6B5.sk1.us-east-1.eks.amazonaws.com

  us-east-1-aap-atw-qatgw:
    type: kubernetes
    environment: qa
    master_url: us-east-1-aap-atw-qatgw

  us-east-2-aap-atw-qadrtgw:
    type: kubernetes
    environment: qa
    master_url: https://75D5257189704D9DB53F26D8EDEA5C71.gr7.us-east-2.eks.amazonaws.com
  
  us-east-1-aap-test-qatgw:
    type: kubernetes
    environment: qa
    master_url: https://927E24D146B07A459A48818874DBF8F4.gr7.us-east-1.eks.amazonaws.com

  us-east-1-aap-primary-atw-prdtgw:
    type: kubernetes
    environment: prd
    master_url: https://9B7224F9AE2DB4905F6724A784A99E7C.sk1.us-east-1.eks.amazonaws.com
  
  us-east-2-aap-atw-prddrtgw:
    type: kubernetes
    environment: prd
    master_url: https://297A5825D0F8DC3B623A83BCFA07AA1D.sk1.us-east-2.eks.amazonaws.com
