app_config:
  artifactorybaseurl: artifactory.ual.com/dockerlocal/airportplatform

# List of all the services for the AppCI
services:

  addflight-airports:
    type: kubernetes
    tier: backend
    artifacts:
      dev:
        type: docker_artifactory
        image: airportplatform/dev/addflight-airports

  addflight-bff:
    type: kubernetes
    tier: backend
    artifacts:
      dev:
        type: docker_artifactory
        image: airportplatform/dev/addflight-bff

  addflight:
    type: kubernetes
    tier: backend
    artifacts:
      dev:
        type: docker_artifactory
        image: airportplatform/bjb/dev/addflight



# Common artifact configuration
artifacts:
  docker_artifactory:
    server: artifactory.ual.com
    repository: dockerlocal
    connector: Jfrog-Artifactory
    auto_trigger: true
    trigger: 
      type: workflow
      name: eks-rolling-basic
      env: 
        name: dev
        infra: us-east-1-aap-atw-devtgw

# Common manifest config for all kubernetes services
manifests:
  kubernetes:
    connector: GitHub-Account-UAL
    repo: AirportOps.CCB.DevSecOps-CCB
    path: SingleTemplate/template
    branch: master
    overrides:
      type: inline
      values: |
        image:
          url: "${app.defaults.artifactorybaseurl}/${env.name}/${service.name}:${artifact.metadata.tag}"

# Workflows to configure
workflows: 
  eks-rolling-basic: {}

# Environment configuration
environments:
  dev:
    type: nonprod

  qa:
    type: nonprod

  stg:
    type: prod

  prd:
    type: prod

# Infrastructure definitions
infrastructure:
  us-east-2-aap-atw-devdrtgw:
    type: kubernetes
    environment: dev
    provider: us-east-2-aap-atw-devdrtgw
    namespace: ${serviceVariable.namespace}

  us-east-1-aap-atw-devtgw:
    type: kubernetes
    environment: dev
    provider: us-east-1-aap-atw-devtgw
    namespace: ${serviceVariable.namespace}

  us-east-1-aap-atw-qatgw:
    type: kubernetes
    environment: qa
    provider: us-east-1-aap-atw-qatgw
    namespace: ${serviceVariable.namespace}

  us-east-2-aap-atw-qadrtgw:
    type: kubernetes
    environment: qa
    provider: us-east-2-aap-atw-qadrtgw
    namespace: ${serviceVariable.namespace}

  us-east-1-aap-test-qatgw:
    type: kubernetes
    environment: qa
    provider: us-east-1-aap-test-qatgw
    namespace: ${serviceVariable.namespace}

  us-east-1-aap-primary-atw-prdtgw:
    type: kubernetes
    environment: prd
    provider: us-east-1-aap-primary-atw-prdtgw
    namespace: ${serviceVariable.namespace}

  us-east-2-aap-atw-prddrtgw:
    type: kubernetes
    environment: prd
    provider: us-east-2-aap-atw-prddrtgw
    namespace: ${serviceVariable.namespace}

# Cloud Providers 
providers:
  us-east-2-aap-atw-devdrtgw:
    type: kubernetes
    environment: dev
    master_url: https://6898A959BEB29879EB78DB7881972045.gr7.us-east-2.eks.amazonaws.com

  us-east-1-aap-atw-devtgw:
    type: kubernetes
    environment: dev
    master_url: https://9FAD057048F1B52E0F1515669463C6B5.sk1.us-east-1.eks.amazonaws.com

  us-east-1-aap-atw-qatgw:
    type: kubernetes
    environment: qa
    master_url: us-east-1-aap-atw-qatgw

  us-east-2-aap-atw-qadrtgw:
    type: kubernetes
    environment: qa
    master_url: https://75D5257189704D9DB53F26D8EDEA5C71.gr7.us-east-2.eks.amazonaws.com
  
  us-east-1-aap-test-qatgw:
    type: kubernetes
    environment: qa
    master_url: https://927E24D146B07A459A48818874DBF8F4.gr7.us-east-1.eks.amazonaws.com

  us-east-1-aap-primary-atw-prdtgw:
    type: kubernetes
    environment: prd
    master_url: https://9B7224F9AE2DB4905F6724A784A99E7C.sk1.us-east-1.eks.amazonaws.com
  
  us-east-2-aap-atw-prddrtgw:
    type: kubernetes
    environment: prd
    master_url: https://297A5825D0F8DC3B623A83BCFA07AA1D.sk1.us-east-2.eks.amazonaws.com
