docker_artifactory_base_url: artifactory.ual.com/dockerlocal/airportplatform

services:


  tcd:
    type: ecs
    artifacts:
      dev: 
        type: docker_registry
        image: library/nginx


# Common artifact configuration
artifacts:
  docker_registry:
    server: docker-hub-public
    # auto_trigger: true
    # trigger: 
    #   type: workflow
    #   name: eks-rolling-basic
    #   env: 
    #     name: dev
    #     infra: us-east-1-aap-atw-devtgw


# Common manifest configuration
manifests:
  ecs:
    connector: micah-demo
    task_definition_path: ecs-deploy/DotNet/TaskDefinition.json
    service_definition_path: ecs-deploy/DotNet/ServiceDefinition.json
    branch: master

workflows: 
  ecs-basic: {}

environments:
  dev:
    type: nonprod

infrastructure:
  cwm-ecs-us-east-1-dev-cluster:
    type: ecs
    environment: dev
    provider: dev
    assign_public_ip: false
    role: arn:aws:iam::560380317052:role/Harness-cwm-tcdecs-dev-us-east-1-Role
    launch_type: fargate
    region: us-east-1
    security_group_ids:
      - sg-09abc2789fc3454e3
    subnet_ids:
      - subnet-060eb67008ada7878
      - subnet-0908d96f54f0a857d
      - subnet-0f4422bb4184c54ae
    vpc: vpc-071b072d13508ae67
    
providers:
  dev:
    type: aws
    environment: dev
    sts_role: arn:aws:iam::560380317052:role/Harness-cvz-pnrlivefeed-dev-us-east-1-Role
