---
connector:
  name: K8s Local Cluster
  identifier: K8s_Local_Cluster
  description: ""
  type: K8sCluster
  spec:
    credential:
      type: InheritFromDelegate
    delegateSelectors:
      - k8s-ng-delegate
