---
DQS-Cluster:
    type: Kubernetes
    environment: DQS
    connector: dqsCluster
    namespace: dev
Prod-Cluster:
    type: Kubernetes
    environment: Prod
    connector: prodCluster
    namespace: prod